---
# local users
local_users:
  # Username with a password
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$aKHHd57oXIFPAR8b$P279AwBfC9wE/ZMi5FJZXTrRmM5CUYUFvd7wS9zkBonZAq7qvhZTXumjA0BgWy8RS./3/iGqx4lPXR5kv4Y64."

# OOB Management network default gateway.
mgmt_interface: Management0
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default

# dns servers.
name_servers:
  - 1.1.1.1
  - 8.8.8.8

# ntp
ntp:
  local_interface:
    name: Management0
    vrf: default
  servers:
  - name: time.google.com
    vrf: default

# Settings for VEOS Deployments

# Update p2p mtu 9000 -> 1500, MTU 9000 not supported in vEOS-LAB.
p2p_uplinks_mtu: 1500

# Adjust default bfd values, to avoid high CPU.
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3